name: ci

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

  schedule:
  - cron: 0 2 * * 3,6

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      ORACLE_HOME: /opt/instantclient_23_7
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
      LD_LIBRARY_PATH: /opt/instantclient_23_7:$LD_LIBRARY_PATH
      OCI_DIR: /opt/instantclient_23_7

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.4', '3.3', '3.2']

    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v5

    - name: Install Oracle instant client
      run: |
        mkdir -p /opt && cd /opt
        curl https://download.oracle.com/otn_software/linux/instantclient/2370000/instantclient-basiclite-linux.x64-23.7.0.25.01.zip --output instantclient.zip
        curl https://download.oracle.com/otn_software/linux/instantclient/2370000/instantclient-sdk-linux.x64-23.7.0.25.01.zip --output instantclient_sdk.zip
        curl https://download.oracle.com/otn_software/linux/instantclient/2370000/instantclient-sqlplus-linux.x64-23.7.0.25.01.zip --output instantclient_sqlplus.zip
        unzip -o instantclient.zip
        unzip -o instantclient_sdk.zip
        unzip -o instantclient_sqlplus.zip

    - name: libaio.so.1 fix with symbolic link
      run: |
        TARGET="/lib/x86_64-linux-gnu/libaio.so.1"
        SOURCE="/lib/x86_64-linux-gnu/libaio.so.1t64"

        # Check if the symbolic link already exists
        if [ ! -e "$TARGET" ]; then
            sudo ln -s "$SOURCE" "$TARGET"
        fi

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: latest
        bundler-cache: true
        cache-version: 1

    - name: Run default task
      run: |
        bundle exec rake
